// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_rVyrqMIojXY4CNsjDLUjWflbsCW8ug',
    appId: '1:502147787922:web:cff99282cc0445dc604a4b',
    messagingSenderId: '502147787922',
    projectId: 'product-db-ccd40',
    authDomain: 'product-db-ccd40.firebaseapp.com',
    databaseURL: 'https://product-db-ccd40-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-ccd40.appspot.com',
    measurementId: 'G-B1F3CY4G15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbx4l3XgZelR_s5rj4lnxr2SDurRoxk6I',
    appId: '1:502147787922:android:b02a82f6ac1d31fd604a4b',
    messagingSenderId: '502147787922',
    projectId: 'product-db-ccd40',
    databaseURL: 'https://product-db-ccd40-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-ccd40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0JfW1_Ya6Yh9ttGvpy7DC4XzE8Nia3o',
    appId: '1:502147787922:ios:a0e350daae81ab30604a4b',
    messagingSenderId: '502147787922',
    projectId: 'product-db-ccd40',
    databaseURL: 'https://product-db-ccd40-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-ccd40.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0JfW1_Ya6Yh9ttGvpy7DC4XzE8Nia3o',
    appId: '1:502147787922:ios:a0e350daae81ab30604a4b',
    messagingSenderId: '502147787922',
    projectId: 'product-db-ccd40',
    databaseURL: 'https://product-db-ccd40-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-ccd40.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP_rVyrqMIojXY4CNsjDLUjWflbsCW8ug',
    appId: '1:502147787922:web:fffd7f9e85f914f6604a4b',
    messagingSenderId: '502147787922',
    projectId: 'product-db-ccd40',
    authDomain: 'product-db-ccd40.firebaseapp.com',
    databaseURL: 'https://product-db-ccd40-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-ccd40.appspot.com',
    measurementId: 'G-GWHD2M22K9',
  );
}
